DOMAIN_SCAN_PATHS = (
    # Environment
    ".env",
    ".env.dev",
    ".env.development",
    ".env.local",
    ".env.production",
    ".env.prod",
    ".env.staging",
    ".env.test",
    ".env.backup",
    ".env.bak",
    ".env.old",
    ".env.local.bak",
    ".env.production.local",
    ".env.save",
    ".env.example",
    ".env.sample",
    ".env.dist",
    ".env~",
    "local.env",
    "dev.env",
    "development.env",
    "backup.env",
    "prod.env",
    "production.env",
    "staging.env",
    "test.env",
    "backup/.env",
    "config/.env",
    "app/.env",
    "api/.env",
    "backend/.env",
    "frontend/.env",
    "server/.env",
    "web/.env",
    "public/.env",
    "laravel/.env",
    "symfony/.env",
    "django/.env",
    "rails/.env",
    "docker/.env",
    "deploy/.env",
    ".envrc",
    ".envrc.local",
    ".envrc.private",

    # Docker
    "Dockerfile",
    "Dockerfile.dev",
    "Dockerfile.prod",
    "Dockerfile.dev.bak",
    "Dockerfile.prod.bak",
    "Dockerfile.production",
    "Dockerfile.staging",
    "Dockerfile.backup",
    "Dockerfile.bak",
    "Dockerfile.old",
    "Dockerfile.save",
    "Dockerfile~",
    "docker-compose.yml",
    "docker-compose.yaml",
    "docker-compose.override.yml",
    "docker-compose.override.yaml",
    "docker-compose.prod.yml",
    "docker-compose.prod.yaml",
    "docker-compose.production.yml",
    "docker-compose.production.yaml",
    "docker-compose.dev.yml",
    "docker-compose.dev.yaml",
    "docker-compose.local.yml",
    "docker-compose.local.yaml",
    "docker-compose.staging.yml",
    "docker-compose.staging.yaml",
    "docker-compose.test.yml",
    "docker-compose.test.yaml",
    "compose.yml",
    "compose.yaml",
    "docker-compose.yml.bak",
    "docker-compose.yaml.bak",
    "docker-compose.override.yml.bak",
    "docker/Dockerfile",
    "docker/docker-compose.yml",
    "docker/docker-compose.yaml",
    ".docker/config.json",
    ".dockercfg",

    # Kubernetes
    "kubernetes.yml",
    "kubernetes.yaml",
    "k8s.yml",
    "k8s.yaml",
    "deployment.yml",
    "deployment.yaml",
    "deploy.yml",
    "deploy.yaml",
    "service.yml",
    "service.yaml",
    "secret.yml",
    "secret.yaml",
    "configmap.yml",
    "configmap.yaml",
    "namespace.yml",
    "namespace.yaml",
    "serviceaccount.yml",
    "serviceaccount.yaml",
    "kustomization.yml",
    "kustomization.yaml",
    "k8s/deployment.yml",
    "k8s/deployment.yaml",
    "k8s/secret.yml",
    "k8s/secret.yaml",
    "k8s/configmap.yml",
    "k8s/configmap.yaml",
    "k8s/kustomization.yml",
    "k8s/kustomization.yaml",
    "k8s/namespace.yml",
    "k8s/namespace.yaml",
    "k8s/serviceaccount.yml",
    "k8s/serviceaccount.yaml",
    "kubernetes/deployment.yml",
    "kubernetes/deployment.yaml",
    "kubernetes/secret.yml",
    "kubernetes/secret.yaml",
    "kubernetes/configmap.yml",
    "kubernetes/configmap.yaml",
    "kubernetes/kustomization.yml",
    "kubernetes/kustomization.yaml",
    "kubernetes/namespace.yml",
    "kubernetes/namespace.yaml",
    "kubernetes/serviceaccount.yml",
    "kubernetes/serviceaccount.yaml",

    # Web server config
    "nginx.conf",
    "nginx/nginx.conf",
    "conf/nginx.conf",
    "sites-enabled/default",
    "sites-available/default",
    "apache.conf",
    "httpd.conf",
    "apache2.conf",
    ".htaccess",
    ".htpasswd",
    "Caddyfile",
    "caddy/Caddyfile",
    "haproxy.cfg",
    "envoy.yaml",
    "envoy.yml",

    # Reverse proxy and ingress
    "traefik.yml",
    "traefik.yaml",
    "traefik.toml",
    "dynamic_conf.yml",
    "dynamic_conf.yaml",
    "ingress.yml",
    "ingress.yaml",
    "k8s/ingress.yml",
    "k8s/ingress.yaml",
    "kubernetes/ingress.yml",
    "kubernetes/ingress.yaml",

    # Helm
    "Chart.yaml",
    "values.yml",
    "values.yaml",
    "values-prod.yml",
    "values-prod.yaml",
    "values-production.yml",
    "values-production.yaml",
    "values-dev.yml",
    "values-dev.yaml",
    "helm/values.yml",
    "helm/values.yaml",
    "charts/values.yml",
    "charts/values.yaml",

    # Nomad, Consul, and Vault
    "nomad.hcl",
    "job.nomad",
    "job.hcl",
    "consul.hcl",
    "consul.json",
    "vault.hcl",
    "vault.json",

    # Deployment platforms
    "Procfile",
    "app.yaml",
    "app.yml",
    "render.yaml",
    "railway.toml",
    "fly.toml",
    "vercel.json",
    "netlify.toml",
    "now.json",

    # Cloud deployment config
    "serverless.yml",
    "serverless.yaml",
    "samconfig.toml",
    "cloudbuild.yaml",
    "cloudbuild.yml",
    "firebase.json",

    # Process managers
    "ecosystem.config.js",
    "ecosystem.config.cjs",
    "pm2.config.js",
    "supervisord.conf",
    "supervisor.conf",

    # CI/CD
    ".github/workflows/deploy.yml",
    ".github/workflows/deploy.yaml",
    ".github/workflows/production.yml",
    ".github/workflows/production.yaml",
    ".gitlab-ci.yml",
    "bitbucket-pipelines.yml",
    "azure-pipelines.yml",
    "Jenkinsfile",
    ".circleci/config.yml",
    ".drone.yml",
    "appveyor.yml",
    ".travis.yml",

    # Ansible and server provisioning
    "ansible.cfg",
    "inventory",
    "inventory.ini",
    "hosts",
    "playbook.yml",
    "playbook.yaml",
    "group_vars/all.yml",
    "group_vars/all.yaml",
    "host_vars/localhost.yml",
    "host_vars/localhost.yaml",

    # Database
    "database.yml",
    "database.yaml",
    "database.json",
    "database.php",
    "db.yml",
    "db.yaml",
    "db.json",
    "db.php",
    "config/database.yml",
    "config/database.yaml",
    "config/database.json",
    "config/database.php",
    "config/db.yml",
    "config/db.yaml",
    "config/db.json",
    "config/db.php",
    "app/config/database.php",

    # Framework credential config
    "config/parameters.yml",
    "config/parameters.yaml",
    "app/config/parameters.yml",
    "app/config/parameters.yaml",
    "sites/default/settings.php",
    "local.xml",
    "app/etc/local.xml",
    "app/etc/env.php",

    # App config
    "app.config.js",
    "app.config.json",
    "appsettings.Development.json",
    "appsettings.Production.json",
    "appsettings.Staging.json",
    "appsettings.json",
    "application.properties",
    "application.yml",
    "application.yaml",
    "config.js",
    "config.json",
    "config.local.js",
    "config.local.json",
    "config.yml",
    "config.yaml",
    "env.js",
    "env.json",
    "local.settings.json",
    "runtime-config.js",
    "runtime-config.json",
    "settings.json",
    "settings.php",

    # Public app config
    "admin/config.json",
    "admin/env.js",
    "api/config.json",
    "api/env.js",
    "assets/app.config.js",
    "assets/config.js",
    "assets/config.json",
    "assets/env.js",
    "assets/env.json",
    "assets/runtime-config.js",
    "build/config.js",
    "build/config.json",
    "build/env.js",
    "js/config.js",
    "js/config.json",
    "js/env.js",
    "public/config.js",
    "public/config.json",
    "public/env.js",
    "public/runtime-config.js",
    "static/config.js",
    "static/config.json",
    "static/env.js",

    # App config profiles
    "config/config.js",
    "config/config.json",
    "config/default.json",
    "config/development.json",
    "config/local.json",
    "config/production.json",
    "config/secrets.json",
    "config/settings.json",
    "config/staging.json",

    # Framework source config
    "src/config.js",
    "src/config.json",
    "src/environments/environment.prod.ts",
    "src/environments/environment.ts",

    # Cloud and service credentials
    ".s3cfg",
    "aws-exports.js",
    "client_secret.json",
    "credentials.json",
    "google-services.json",
    "service-account.json",

    # Package manager credentials
    ".npmrc",
    ".pypirc",
    "auth.json",

    # Infrastructure as code
    ".terraformrc",
    "main.tf",
    "variables.tf",
    "outputs.tf",
    "terraform.tfvars",
    "terraform.tfvars.json",
    "pulumi.yaml",
    "Pulumi.yaml",
    "Pulumi.dev.yaml",
    "Pulumi.prod.yaml",

    # VCS metadata
    ".git/config",
    ".git-credentials",
    ".hg/hgrc",

    # Secret dumps
    "passwords.txt",
    "password.txt",
    "passwd.txt",
    "creds.txt",
    "credentials.txt",
    "secrets.txt",
    "secret.txt",
    "tokens.txt",
    "token.txt",
    "keys.txt",
    "apikeys.txt",
    "api_keys.txt",
    "access_tokens.txt",

    # Secret/config backups
    "config.php.bak",
    "wp-config.php.bak",
    "wp-config.php~",
    "wp-config.php.save",
    "config.inc.php.bak",
    "secrets.json",
    "secrets.yml",
    "secrets.yaml",
)
