HEX_ENTROPY_MAX = 4.5
B64_ENTROPY_MAX = 6.0
MAX_LINE_LENGTH = 50000
MAX_REPEAT_RUN = 1000
MAX_WORKERS_MULTIPLIER = 2


class CliArgs:
    HEX_ENTROPY_THRESHOLD = 3.0
    B64_ENTROPY_THRESHOLD = 4.5
    MIN_STRING_LENGTH = 10
    MIN_CONFIDENCE = 75
    MAX_WORKERS = 4
    REVEAL_FINDINGS = False
    LOG_LEVEL = "INFO"
